### ISSUE TITLE
Issue on page /valais.html

### ISSUE THREAD

**Issue by majavs** [hammerdirt-analyst/cantonal_reports#2]
Your issue content here.

Bonjour,

Je teste Github.
 Je voulais vous indiquer qu'il y a la station de Charmey du canton Fribourg sur le rapport VS. 
Une cartographie avec les différents sites d'échantillonnage sur le canton pourrait être une bonne idée, une fois qu'on a défini le contenu.

Bonne journée

Marion

**Comment by hammerdirt-analyst** [comment]
Merci!,

Nous procéderons à cette modification ce soir.  

J'ai ouvert un dossier consacré à l'affichage des cartes et à la manière dont elles sont affichées #4 . Pour le Valais, nous pouvons faire référence à deux cartes du rapport fédéral :

Le bassin du Rhône :
![image](https://github.com/hammerdirt-analyst/cantonal_reports/assets/63396080/66e0f393-796a-4000-b194-b95349d8bae2)

Les Alpes et le Jura
![image](https://github.com/hammerdirt-analyst/cantonal_reports/assets/63396080/f7af42b6-e43c-4a27-aa07-88073b3c8a56)

**Comment by majavs** [comment]
Oui elle sont bien les cartes.

petite question de compréhension, les données sur la plage bleue du Bouveret correspondent à 7 échantillons entre 2015 et 2022? C'est les données que vous aviez demandé à d'autres organisations.

**Comment by hammerdirt-analyst** [comment]
Bonjour,

Les données du Bouveret datent de 2022 et ont été collectées par [l'ASL](https://asleman.org/). Partie du projet [Plastock](https://hammerdirt-analyst.github.io/plastock/)

J'ai inclus la liste des associations qui ont collecté des données dans la section des [variables aléatoires](https://hammerdirt-analyst.github.io/cantonal_reports/random_variables.html).

Nous commencerons par une carte de base. S'il existe des cartes vectorielles (fichiers .shp) que nous pouvons utiliser et qui contiennent des données hydrologiques (débits, altitude), elles peuvent être intégrées dans l'analyse de base.

**Comment by hammerdirt-analyst** [comment]
Bonjour, 
La correction a été faite avec le commit https://github.com/hammerdirt-analyst/cantonal_reports/commit/f7768d5513f3792d88cd90c7540ba3e81736e3bb.

De plus, les fichiers .shp de base pour les cartes ont été ajoutés au repo.
