### ISSUE TITLE
Issue on page /le_leman.html

### ISSUE THREAD

**Issue by majavs** [hammerdirt-analyst/cantonal_reports#3]
Your issue content here.

Bonjour, Une définition des catégories "haut-lac, grand-lac et petit-lac" ou une image permettrait de connaître quelles sont les zones concernées. 

Bonne journée,

Marion

**Comment by hammerdirt-analyst** [comment]
Bonjour Marion,

Je déplacerai cette question dans les demandes de fonctionnalités pour ce rapport. Les données de l'analyse sont projetées sur la carte. Nous attendons généralement que certaines décisions soient prises concernant :

1. les codes d'intérêt
2. les valeurs d'utilisation du sol qui nous intéressent
3. la nomenclature standard
4. les noms de lieux et l'orthographe corrects
5. éléments de style ...

Il y a une très bonne version de la carte du lac Leman ici :

https://hammerdirt-analyst.github.io/IQAASL-End-0f-Sampling-2021/lac-leman.html

![image](https://github.com/hammerdirt-analyst/cantonal_reports/assets/63396080/99a8b316-2cae-44ca-9811-e1f382bb812a)
